version: '3.9'
services:
  webpage:
    container_name: linuxipsum-website
    image: linuxipsum-website
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "20245:80"
